### ISSUE TITLE
Опечатка в fork_server.cpp

### ISSUE THREAD

**Issue by iklingen** [sdukshis/coroutines-epoll-example#1]
Здравствуйте, Павел! Вчера посмотрел Ваш ролик про использование корутин на примере эхо-сервера (https://www.youtube.com/watch?v=iSfrR553LeY). Очень понравилась лекция! Спасибо Вам!

В примере с форком есть небольшой недочет или опечатка. После форка идет проверка на `! chaild`, а в следующей ветке условного оператора на `chaild == -1`. Если форк сбойнет, то все равно выполниться первая ветка. Нужно либо поменять местами ветки, либо в первой ветке сделать условие `chaild > 0`.

**Comment by sdukshis** [comment]
Добрый день!

Я рад, что мой вебинар понравился.

По поводу опечатки. Я не вижу там логических ошибок. Если fork() завершиться с ошибкой и в Child запишется -1, то !-1 вернут false и основная ветка с кодом дочернего процесса не выполнится.

При этом выполнится else if в родительском процессе.
